### ISSUE TITLE
Oracle Free Tier 4 core - 24 GB VM

### ISSUE THREAD

**Issue by EMPAT94** [cloudcommunity/Cloud-Free-Tier-Comparison#13]
Yes, oracle offers a _very_ generous 24 GB with 4 ARM Core VM. It can be broken down into multiple smaller instances too. I am using it currently and I believe many people will find it useful!

Image from [Oracle Free Tier](https://www.oracle.com/cloud/free/):

![image](https://user-images.githubusercontent.com/9110181/156184743-8805217f-148d-483f-8736-5ecf2ca3ef8f.png)

---

Excerpt from [Oracle Always Free Resources](https://docs.oracle.com/en-us/iaas/Content/FreeTier/freetier_topic-Always_Free_Resources.htm):

> Available Shapes
>
> Micro instances (AMD processor): All tenancies get up to two Always Free VM instances using the VM.Standard.E2.1.Micro [shape](https://docs.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm#Compute_Shapes), which has an AMD processor.
>
> Ampere A1 Compute instances (Arm processor): All tenancies get the first 3,000 OCPU hours and 18,000 GB hours per month for free for VM instances using the VM.Standard.A1.Flex [shape](https://docs.oracle.com/en-us/iaas/Content/Compute/References/computeshapes.htm#Compute_Shapes), which has an [Arm processor](https://docs.oracle.com/en-us/iaas/Content/Compute/References/arm.htm#arm). For Always Free tenancies, this is equivalent to 4 OCPUs and 24 GB of memory.

Imho worth adding to readme.

**Comment by Jan69** [comment]
some people claim the ARM machine also has faster networking, which would be another benefit

**Comment by danwdart** [comment]
Yes, you can still see the offering but provisioning always returns an error being out of resources.

**Comment by Jan69** [comment]
> Yes, you can still see the offering but provisioning always returns an error being out of resources.

out of resources just means you need to wait until some get available, could be days, weeks, months, people reported the arm machines to be unavailable back when those were announced too, just because everyone wanted one, and there's only so much physical hardware

just can't get it NOW, but offer's still there ;)
