### ISSUE TITLE
Repository name is too long

### ISSUE THREAD

**Issue by APratham** [cloudcommunity/Cloud-Free-Tier-Comparison#6]
I feel that the name of the repository is too long. Kindly change it to something that is shorter. concise and still conveys the same meaning

**Comment by karentamrazyan** [comment]
thanks @APratham . Just spotted your issue/comment. It makes sense. Any name suggestions are welcome.

**Comment by APratham** [comment]
@karentamrazyan, as told in the original comment, it is just a suggestion, and it is only because there is no real need for such a long name. GitHub always favours short, memorable names for repositories. While I don't have the original thoughts from that time, here are a few suggestions over the top of my head: 

cloud-for-free
free-tier-overview
free-cloud-usage

Maybe even build-on-cloud

Please let me know if any of these interest you. If not, then we can work towards choosing another, better alternative name

**Comment by karentamrazyan** [comment]
How about:

free-cloud-resources

?

**Comment by karentamrazyan** [comment]
eventually changed the name to "Cloud-Free-Tier-Comparison". It's also a search keyword. Hence, should be nicely discoverable from the outside. Thanks for this advice @APratham!
